export const SCREEN_NAMES = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  HOME: 'HOME',
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
  CATEGORY_QUESTIONS: 'CATEGORY_QUESTIONS',
  ADD_NEW_QUESTION: 'ADD_NEW_QUESTION',
  QUESTION: 'QUESTION',
  TOP_QUESTIONS: 'TOP_QUESTIONS',
}
